name: 'SWE-agent Resolver'
description: 'Uses SWE-agent to automatically fix issues.'
author: 'GitHub Copilot'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for authentication.'
    required: true
  CONFIG_FILE:
    description: 'Path to the configuration file for SWE-agent.'
    required: false
    default: '.github/swe-agent-config.json' # Example default
  # Add other inputs as needed by your TypeScript action

runs:
  using: 'docker'
  image: 'Dockerfile'
  # For Node.js actions, you might use:
  # using: 'node20'
  # main: 'dist/index.js'

outputs:
  RESULT_MESSAGE:
    description: "A message indicating the result of the agent's attempt.""
  # Define other outputs as needed

# Branding (optional)
branding:
  icon: 'code' # Choose an icon from https://feathericons.com/
  color: 'blue' # Choose a color like yellow, blue, green, etc.

# Add any environment variables your action needs
# env:
#   MY_ENV_VAR: 'my_value'