name: 'SWE-Agent GitHub Action Wrapper'
description: 'Lightweight wrapper for seamless SWE-agent integration with GitHub issues and PRs'
author: 'nimishchaudhari'

branding:
  icon: 'code'
  color: 'blue'

inputs:
  model_name:
    description: 'AI model to use (e.g., gpt-4o-mini, claude-3-5-sonnet-latest, deepseek/deepseek-chat)'
    required: true
    default: 'gpt-4o-mini'
  
  trigger_phrase:
    description: 'Phrase to trigger the action in comments'
    required: false
    default: '@swe-agent'
  
  max_cost:
    description: 'Maximum cost limit for SWE-agent execution (USD)'
    required: false
    default: '5.00'
  
  tools:
    description: 'Comma-separated list of tools SWE-agent can use'
    required: false
    default: 'str_replace_editor,bash'
  
  debug_mode:
    description: 'Enable debug logging'
    required: false
    default: 'false'

outputs:
  status:
    description: 'Execution status (success, failure, skipped)'
  
  cost_estimate:
    description: 'Estimated cost of the execution'
  
  comment_url:
    description: 'URL of the GitHub comment with results'

runs:
  using: 'docker'
  image: 'Dockerfile'