# Example workflow: SWE-Agent with OpenRouter (Access to multiple models)
name: SWE-Agent with OpenRouter

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited, synchronize]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  swe-agent:
    runs-on: ubuntu-latest
    name: AI Code Assistant (OpenRouter)
    
    steps:
      - name: SWE-Agent Resolver
        uses: nimishchaudhari/swe-agent-resolver@v1
        with:
          model_name: 'openrouter/anthropic/claude-3.5-sonnet'  # or openrouter/openai/gpt-4, openrouter/qwen/qwen-32b
          trigger_phrase: '@swe-agent'
          max_cost: '6.00'
          allowed_tools: 'str_replace_editor,bash,file_viewer,python_executor,git_tool'
          custom_instructions: 'Use the most appropriate model for the task complexity.'
          fallback_models: 'openrouter/openai/gpt-4,openrouter/meta-llama/llama-3-70b-instruct'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}