name: SWE-Agent Cost-Optimized (DeepSeek Primary)

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]

jobs:
  swe-agent:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@swe-agent')) ||
      (github.event_name == 'pull_request')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: SWE-Agent Resolver (Cost-Optimized)
        uses: ./
        with:
          # Primary: DeepSeek (most cost-effective)
          model_name: 'deepseek/deepseek-chat'
          trigger_phrase: '@swe-agent'
          max_cost: '2.00'  # Lower budget
          
          # Cost-optimized fallback chain
          fallback_models: 'deepseek/deepseek-coder,gpt-3.5-turbo,groq/llama2-70b-4096'
          
          allowed_tools: 'str_replace_editor,bash,file_viewer'
          workspace_timeout: '1200'  # 20 minutes
          debug_mode: 'false'
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Budget Alert
        if: failure()
        run: |
          echo "⚠️ SWE-Agent task may have exceeded budget or failed" >> $GITHUB_STEP_SUMMARY
          echo "Consider increasing max_cost or using a higher-tier model" >> $GITHUB_STEP_SUMMARY