name: SWE-Agent with OpenAI GPT-4.1-mini

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize]
  pull_request_review_comment:
    types: [created]

jobs:
  swe-agent:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@swe-agent')) ||
      (github.event_name == 'pull_request') ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@swe-agent'))
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: SWE-Agent Resolver
        uses: ./
        with:
          model_name: 'gpt-4.1-mini'
          trigger_phrase: '@swe-agent'
          max_cost: '5.00'
          allowed_tools: 'str_replace_editor,bash,file_viewer,python_executor'
          fallback_models: 'gpt-3.5-turbo,claude-3-haiku-20240307'
          workspace_timeout: '1800'
          debug_mode: 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: swe-agent-logs
          path: /tmp/swe-agent-logs/
          retention-days: 7