# Example workflow: SWE-Agent with Anthropic Claude models
name: SWE-Agent with Anthropic Claude

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited, synchronize]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  swe-agent:
    runs-on: ubuntu-latest
    name: AI Code Assistant (Claude)
    
    steps:
      - name: SWE-Agent Resolver
        uses: nimishchaudhari/swe-agent-resolver@v1
        with:
          model_name: 'claude-3-5-sonnet-latest'  # or claude-3-haiku-20240307
          trigger_phrase: '@swe-agent'
          max_cost: '8.00'  # Claude has higher token costs
          allowed_tools: 'str_replace_editor,bash,file_viewer,python_executor,git_tool'
          custom_instructions: 'Provide detailed explanations and consider edge cases.'
          fallback_models: 'claude-3-haiku-20240307,gpt-4o'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Fallback API key for OpenAI models
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}