# Example workflow: SWE-Agent with Multiple Providers and Smart Fallbacks
name: SWE-Agent Multi-Provider Setup

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited, synchronize]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  swe-agent:
    runs-on: ubuntu-latest
    name: AI Code Assistant (Multi-Provider)
    
    steps:
      - name: SWE-Agent Resolver
        uses: nimishchaudhari/swe-agent-resolver@v1
        with:
          model_name: 'claude-3-5-sonnet-latest'  # Primary model
          trigger_phrase: '@swe-agent'
          max_cost: '7.00'
          allowed_tools: 'str_replace_editor,bash,file_viewer,python_executor,git_tool'
          custom_instructions: 'Prioritize code quality, security, and maintainability.'
          # Comprehensive fallback chain across providers
          fallback_models: 'gpt-4o,deepseek/deepseek-chat,openrouter/anthropic/claude-3.5-sonnet,groq/llama2-70b-4096'
          workspace_timeout: '1800'
          debug_mode: 'false'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Primary provider
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Fallback providers
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          deepseek_api_key: ${{ secrets.DEEPSEEK_API_KEY }}
          openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}
          groq_api_key: ${{ secrets.GROQ_API_KEY }}