# Example workflow: SWE-Agent with Azure OpenAI (Enterprise)
name: SWE-Agent with Azure OpenAI

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited, synchronize]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  swe-agent:
    runs-on: ubuntu-latest
    name: AI Code Assistant (Azure)
    
    steps:
      - name: SWE-Agent Resolver
        uses: nimishchaudhari/swe-agent-resolver@v1
        with:
          model_name: 'azure/gpt-4'  # Must match your Azure deployment name
          trigger_phrase: '@swe-agent'
          max_cost: '10.00'
          allowed_tools: 'str_replace_editor,bash,file_viewer,python_executor,git_tool'
          custom_instructions: 'Follow enterprise security guidelines and coding standards.'
          workspace_timeout: '2400'  # 40 minutes for complex enterprise tasks
          github_token: ${{ secrets.GITHUB_TOKEN }}
          azure_openai_api_key: ${{ secrets.AZURE_OPENAI_API_KEY }}
          azure_openai_endpoint: ${{ vars.AZURE_OPENAI_ENDPOINT }}
          azure_openai_api_version: ${{ vars.AZURE_OPENAI_API_VERSION }}